#! /bin/bash

/run &>/dev/null &
n=0
until [ $n -ge 10 ]
do
  /decktape/bin/phantomjs /decktape/decktape.js http://localhost:8000 /index.pdf 1>&2 && break
  n=$((n+1))
  sleep 1
done
if [[ -f /index.pdf ]]; then
  cat /index.pdf
else
  echo "Failed to create PDF" 1>&2
fi
kill %1 &>/dev/null
exit
